name: CI Monorepo

on:
  push:
    branches: ["main", "develop", "master", "feature"]
  pull_request:
    branches: ["main", "feature", "develop", "master"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      user-service: ${{ steps.filter.outputs.user-service }}
      product-service: ${{ steps.filter.outputs.product-service }}
      order-service: ${{ steps.filter.outputs.order-service }}
      notification-service: ${{ steps.filter.outputs.notification-service }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            user-service:
              - 'services/user-service/**'
            product-service:
              - 'services/product-service/**'
            order-service:
              - 'services/order-service/**'
            notification-service:
              - 'services/notification-service/**'

  test-user-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.user-service == 'true'
    uses: ./.github/workflows/test-service.yml
    with:
      service: user-service
      working_directory: ./services/user-service

  test-product-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.product-service == 'true'
    uses: ./.github/workflows/test-service.yml
    with:
      service: product-service
      working_directory: ./services/product-service

  test-order-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.order-service == 'true'
    uses: ./.github/workflows/test-service.yml
    with:
      service: order-service
      working_directory: ./services/order-service

  test-notification-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.notification-service == 'true'
    uses: ./.github/workflows/test-service.yml
    with:
      service: notification-service
      working_directory: ./services/notification-service